### ISSUE TITLE
Error with opencollective in postinstall script on the heroku.

### ISSUE THREAD

**Issue by pro2s** [nuxt-contrib/opencollective#61]
Hi,

When I try to deploy my application a get an error (postinstall script in bootstrap-vue)
> opencollective || exit 0
npm ERR! Cannot read property 'length' of undefined

engines.node (package.json):  12.18.2
engines.npm (package.json):   6.14.5

it seems that this is the reason that the heroku does not set `process.argv` and `opencollective` command crashes on this place:
https://github.com/nuxt-contrib/opencollective/blob/585e2aeed8088fb0f8dcf0306a5cf70d352bc49f/bin/opencollective.js#L3

Is there any workaround?

**Comment by pi0** [comment]
Hi @pro2s thanks for making issue. But just to ensure error is from bin, can you please share full stack trace or a screenshot of error in heroku?

**Comment by pro2s** [comment]
Hi @pi0, It is definitely from postinstall, but unfortently I have not full debug log.
![image](https://user-images.githubusercontent.com/3265359/96273437-07043180-0fd8-11eb-959d-28b016ecbe4a.png)

**Comment by pro2s** [comment]
@pi0 there is full log:
```
       npm info lifecycle bootstrap-vue@2.17.3~install: bootstrap-vue@2.17.3
       npm info lifecycle bootstrap-vue@2.17.3~postinstall: bootstrap-vue@2.17.3
       
       > bootstrap-vue@2.17.3 postinstall /tmp/build_e8013a1b_/node_modules/bootstrap-vue
       > opencollective || exit 0
       
       npm verb lifecycle bootstrap-vue@2.17.3~postinstall: unsafe-perm in lifecycle true
       npm verb lifecycle bootstrap-vue@2.17.3~postinstall: PATH: /tmp/build_e8013a1b_/.heroku/node/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/tmp/build_e8013a1b_/node_modules/bootstrap-vue/node_modules/.bin:/tmp/build_e8013a1b_/node_modules/.bin:/tmp/build_e8013a1b_/.heroku/node/bin:/tmp/build_e8013a1b_/.heroku/yarn/bin:/app/.heroku/php/sbin:/app/.heroku/php/bin:/app/.heroku/php/sbin:/app/.heroku/php/bin:/app/.heroku/php/sbin:/app/.heroku/php/bin:/usr/local/bin:/usr/bin:/bin:/app/vendor/bin
       npm verb lifecycle bootstrap-vue@2.17.3~postinstall: CWD: /tmp/build_e8013a1b_/node_modules/bootstrap-vue
       npm info lifecycle axios@0.18.1~preinstall: axios@0.18.1
       npm info lifecycle is-buffer@2.0.4~preinstall: is-buffer@2.0.4
       npm info lifecycle is-buffer@2.0.4~install: is-buffer@2.0.4
       npm info lifecycle is-buffer@2.0.4~postinstall: is-buffer@2.0.4
       npm info lifecycle axios@0.18.1~install: axios@0.18.1
       npm info lifecycle axios@0.18.1~postinstall: axios@0.18.1
       npm info lifecycle undefined@undefined~install: undefined@undefined
       npm info lifecycle undefined@undefined~postinstall: undefined@undefined
       npm verb stack TypeError: Cannot read property 'length' of undefined
       npm verb stack     at _incorrectWorkingDirectory (/tmp/build_e8013a1b_/.heroku/node/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:114:60)
       npm verb stack     at /tmp/build_e8013a1b_/.heroku/node/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:86:44
       npm verb stack     at /tmp/build_e8013a1b_/.heroku/node/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:218:12
       npm verb stack     at callback (/tmp/build_e8013a1b_/.heroku/node/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:295:20)
       npm verb stack     at FSReqCallback.oncomplete (fs.js:168:5)
       npm verb cwd /tmp/build_e8013a1b_
       npm verb Linux 4.4.0-1078-aws
       npm verb argv "/tmp/build_e8013a1b_/.heroku/node/bin/node" "/tmp/build_e8013a1b_/.heroku/node/bin/npm" "ci" "--production=false" "--unsafe-perm" "--userconfig" "/tmp/build_e8013a1b_/.npmrc"
       npm verb node v12.18.2
       npm verb npm  v6.14.5
       npm ERR! Cannot read property 'length' of undefined
       npm verb exit [ 1, true ]
```

**Comment by pi0** [comment]
Well then it makes sense:

> npm ERR! Cannot read property 'length' of undefined

This error seems coming from: 

>        npm verb stack     at _incorrectWorkingDirectory (/tmp/build_e8013a1b_/.heroku/node/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:114:60)

Which is from a package without `name` and version fields (that's why there is `undefined@undefined` in the logs)

Here is also source to `npm-lifecycle`: https://github.com/npm/npm-lifecycle/blob/bfb6f73853a222a3f35a1a6651b0756816e2ed87/index.js#L114

There is also an open pull-request for fix: https://github.com/npm/npm-lifecycle/pull/48
